<#ftl encoding="UTF-8">
<#import "/mylib.ftl" as mylib>
<#if !entity.root>
/**
 * WARNING: Generated code! Changes will be overriden!
 * Generated by: java/ProtoValue.ftl
 */
syntax = "proto3";
option java_multiple_files = true;
package ${subnamespace}.${entity.namespace};

import "google/protobuf/wrappers.proto";

<#if (entity.comment)??>// $entity.comment</#if>
message Proto${entity.name}Value {
	<#list entity.attributes as attribute>
    ${proto[attribute.type]} ${attribute.name} = ${attribute?index + 1};
    </#list>
}
</#if>
