<#ftl encoding="UTF-8">
<#import "/mylib.ftl" as mylib>
<#if !entity.root>
/**
 * WARNING: Generated code! Changes will be overriden!
 * Generated by: java/ProtoValueFilter.ftl
 */
syntax = "proto3";
option java_multiple_files = true;
package ${subnamespace}.${entity.namespace};

import "google/protobuf/wrappers.proto";

message Proto${entity.name}ValueFilter {
	<#list entity.attributes as attribute>
    ${proto[attribute.type]} ${attribute.name} = ${attribute?index*100 + 1};
    ${proto[attribute.type]} ${attribute.name}_IN = ${attribute?index*100 + 2};
    ${proto[attribute.type]} ${attribute.name}_MAX = ${attribute?index*100 + 3};
    ${proto[attribute.type]} ${attribute.name}_FROM = ${attribute?index*100 + 4};
    ${proto[attribute.type]} ${attribute.name}_TO = ${attribute?index*100 + 5};
    </#list>
}
</#if>
