<#ftl encoding="UTF-8">
<#import "/mylib.ftl" as mylib>
<#if !entity.root && entity.parent??>
/**
 * WARNING: Generated code! Changes will be overriden!
 * Generated by: java/ProtoKey.ftl
 */
syntax = "proto3";
option java_multiple_files = true;
package ${subnamespace}.${entity.namespace};

import "google/protobuf/wrappers.proto";
import "babylon_schema/patient/Proto${entity.parent.name}Key.proto";
import "babylon_schema/common/ProtoGenerationOptions.proto";

message Proto${entity.name}Key {
    // not needed anymore
    // option (com.babylonhealth.common.as_key) = true;
    google.protobuf.StringValue id = 1;
    com.babylonhealth.patient.Proto${entity.parent.name}Key parent = 2;
}
</#if>
